service: auth

permissions:
  - key: 'user.read'
    description: 'Read user data'
    allowKey: false

  - key: 'user.write'
    description: 'Write user data'
    allowKey: false

  - key: 'service.read'
    description: 'Read all services'
    allowKey: true

  - key: 'service.write'
    description: 'Modify all services'
    allowKey: true

  - key: 'role.read'
    description: 'Read all roles'
    allowKey: true

  - key: 'role.write'
    description: 'Modify any role'
    allowKey: true

  - key: 'permission.read'
    description: 'Read all permissions'
    allowKey: true

  - key: 'permission.write'
    description: 'Modify all permissions'
    allowKey: true
