service: auth

permissions:
  - key: 'user.read'
    description: 'Read user data'
    scopes:
      - 'user'

  - key: 'user.write'
    description: 'Write user data'
    scopes:
      - 'user'

  - key: 'service.read'
    description: 'Read all services'
    scopes:
      - 'user'
      - 'api-key'

  - key: 'service.write'
    description: 'Modify all services'
    scopes:
      - 'user'
      - 'api-key'

  - key: 'role.read'
    description: 'Read all roles'
    scopes:
      - 'user'
      - 'api-key'

  - key: 'role.write'
    description: 'Modify any role'
    scopes:
      - 'user'
      - 'api-key'

  - key: 'permission.read'
    description: 'Read all permissions'
    scopes:
      - 'user'
      - 'api-key'

  - key: 'permission.write'
    description: 'Modify all permissions'
    scopes:
      - 'user'
      - 'api-key'
